# create package tag
name: Update Version and Tag

on:
  push:
    branches:
      - master

jobs:
  version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://npm.pkg.github.com'

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Create release tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          pnpm version minor -m 'create new version v%s' --tag-version-prefix='v'

      - name: Set next development version
        run: |
          pnpm version prerelease --no-git-tag-version
          git commit -a -m "[skip ci] Create next snapshot version"
          # git push origin

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          tags: true
